USE retail_ai;
COMMIT ;
-- Lets start analysis--
-- identifying key metrics for sales perfomance --


## FIND NUMBER OF PURCHASE IN YEAR

SELECT COUNT(CUSTOMER_ID) AS TOTAL_PURCHASE , YEAR(TXN_DT) AS YEAR
FROM transactions
GROUP BY  YEAR
ORDER BY 1 DESC ;

SELECT COUNT(CUSTOMER_ID) AS VISITS , YEAR(TXN_DT) AS YEAR
FROM transactions
WHERE CUSTOMER_TYPE = "LOYAL_CARD" 
GROUP BY  YEAR
ORDER BY 1 DESC ;

SELECT COUNT(CUSTOMER_ID) AS PURCAHSE_NO_CARD , YEAR(TXN_DT) AS YEAR
FROM transactions
WHERE CUSTOMER_TYPE = "NO CARD" 
GROUP BY  YEAR
ORDER BY 1 DESC ;



## FIND TOTAL PURCHASE VALUE IN YEAR WISE

SELECT COUNT(CUSTOMER_ID) AS TOTAL_PURCHASE , ROUND(SUM(NET_AMT),0) AS PURCHASE_VALUE , YEAR(TXN_DT) AS YEAR
FROM transactions
GROUP BY  YEAR
ORDER BY 2 DESC ;

## FIND TOTAL PURCHASE VALUE IN YEAR WISE BY LOYALITY CARDED CUSTOMERS

SELECT COUNT(CUSTOMER_ID) AS TOTAL_PURCHASE , ROUND(SUM(NET_AMT),0) AS PURCHASE_VALUE , YEAR(TXN_DT) AS YEAR
FROM transactions
WHERE CUSTOMER_TYPE = "LOYAL_CARD" 
GROUP BY  YEAR
ORDER BY 2 DESC ;

## FIND TOTAL PURCHASE VALUE  YEAR WISE - NO CARDED CUSTOMERS

SELECT 
    COUNT(CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(NET_AMT), 0) AS PURCHASE_VALUE,
    YEAR(TXN_DT) AS YEAR
FROM
    transactions
WHERE
    CUSTOMER_TYPE = 'NO CARD'
GROUP BY YEAR
ORDER BY 2 DESC;

/* THOUGH THERE IS A SLIGHT DECREASE OF 3000 TRANSACTION BY LOYAL CUSTOMERS COMPARED TO 2010
PURCHASE VALUE IS MORE COMLPARED TO 2010 BY 66000
--WHEN TOTAL TRANSACTION OF NON CARDED CUSTOMERS WHERE ALAYZED THERE IS 40% DECEASE IN PURCHASE 
AND ALSO  33 PERCENT DECREASE IN PURCHASE VALUE COMPARED TO PREVIOUS YEAR */

## SUMMARIZING FINDINGS INTO ONE TABLE

SELECT 
    CUSTOMER_TYPE,
    COUNT(CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(NET_AMT), 0) AS PURCHASE_VALUE,
    YEAR(TXN_DT) AS YEAR
FROM
    transactions
GROUP BY 1 , 4
ORDER BY 3 DESC;

-- SUMMARY TABLE SHOWS THAT THE DECRESE IN OVERALL SALES WAS MOSTLY DUE TO NO CARDED CUTOMERS--
-- LOYALITY CARD CUSTOMERS WHERE CONSISTENT IN PURCHASE VALUE WHICH SHOWS LOYALITY PROGRAMME IS SUCCESSFULL --

## NOW LETS ANALYZE WHY THERE WAS A DECREASE OF 40% IN PURCHASE IN 2011
## find average discount recieved by customers

SELECT 
    CUSTOMER_TYPE,
    ROUND(AVG(DISC_MARGIN) * 100) AS PERCENT_DISC,
    YEAR(TXN_DT) AS YEAR
FROM
    transactions
GROUP BY 1 , 3
ORDER BY 2 ASC;

## LOYALITY CARD CUSTOMERS HAS ENJOYED MORE DISCOUNT COMPARECD TO NON CARDER CUSTOMERS IE 3% MORE IN EACH YEAR
## THERE WAS AN REDUCTION OF TWO PERCENTAGE OVERALL DISCOUNT FOR BOTH CUSTOMER TYPE COMPARED TO 2010 WHICH MAY HAVE AFFECTED THE SALES

-- LETS FIND OVER ALL VALUE PER PURCHASE --

SELECT 
    CUSTOMER_TYPE,
    ROUND(ROUND(SUM(NET_AMT), 0) / COUNT(CUSTOMER_ID)) AS AMT_PER_PURCHASE,
    SUM(ITEM_QTY) / COUNT(CUSTOMER_ID) AS AVERAGE_UNITS,
    YEAR(TXN_DT) AS YEAR
FROM
    transactions
GROUP BY 1 , 4
ORDER BY 2 DESC;

## AVERAGE PURCHASE VALUE OF CARDED MEMBERS HAS INCREASED BY 7 AND NO CARD CUSTOMERS BY 10
## THIS MAY BE DUE TO INCREASED AVERAGE PRICE FOR PRODUCTS 

-- lets analyse which category products shows in decline in sales for non carded customers --

SELECT 
    t.CUSTOMER_TYPE,
	p.CATEGORY,
    COUNT(t.CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(t.NET_AMT), 0) AS PURCHASE_VALUE,
    YEAR(t.TXN_DT) AS YEAR
FROM
    transactions t
        JOIN
    product p ON t.UPC_ID = p.UPC_id
WHERE t.CUSTOMER_TYPE = "NO CARD"
GROUP BY 2 , 5
ORDER BY 3 DESC;

## total purchse and total sales value was significantly reduced in MOUTH WASH CATEGORY

-- lets analyse why mouth wash category sales declied for non carded customers--

SELECT 
    t.CUSTOMER_TYPE,
	p.CATEGORY,
    COUNT(t.CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(t.NET_AMT), 0) AS PURCHASE_VALUE,
	ROUND(AVG(DISC_MARGIN) * 100) AS PERCENT_DISC,
    YEAR(t.TXN_DT) AS YEAR
FROM
    transactions t
        JOIN
    product p ON t.UPC_ID = p.UPC_id
WHERE t.CUSTOMER_TYPE = "NO CARD" 
GROUP BY 2 , 6
ORDER BY 3 DESC;


-- COMPARE CATEGORY WISE SALES FOR BOTH CUSTOMER TYPE --

SELECT 
    t.CUSTOMER_TYPE,
	p.CATEGORY,
    COUNT(t.CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(t.NET_AMT), 0) AS PURCHASE_VALUE,
    ROUND(AVG(DISC_MARGIN) * 100) AS PERCENT_DISC,
    YEAR(t.TXN_DT) AS YEAR
FROM
    transactions t
        JOIN
    product p ON t.UPC_ID = p.UPC_id
GROUP BY 1, 2 , 6
ORDER BY 3 DESC;

/*
 KEY INSIGHTS : 
 MOuTH WASH  IS THE MOST PURCHASED CATEGORY FOR BOTH CUSTOMER TYPE
 LOYALITY CARD OWNERS ENJOY A HIGHER DISCOUNT COMPARED TO NON CARDED MEMBERS IN THIS CATEGORY
 DENTAL FLOWS AND MOUTH SPRAY SHOWS SAME DISCOUNT FOR BOTH TYPE OF CUSTOMERS AND THUS SIMILIAR SALES */
 
 -- IDENTIFY WHICH BRAND HAS MOST SALES IN MOUTH WASH CATEGORY IN NON CARDED CUSTOMER SEGMENT--

SELECT 
    t.CUSTOMER_TYPE,
	p.CATEGORY,
    p.BRAND,
    COUNT(t.CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(t.NET_AMT), 0) AS PURCHASE_VALUE,
    ROUND(AVG(NET_AMT/ITEM_QTY),2) AS AVERAGE_PRICE,
    ROUND(AVG(DISC_MARGIN) * 100) AS PERCENT_DISC,
    YEAR(t.TXN_DT) AS YEAR
FROM
    transactions t
        JOIN
    product p ON t.UPC_ID = p.UPC_id
WHERE p.CATEGORY = "MOUTHWASH" AND t.CUSTOMER_TYPE = "NO CARD"
GROUP BY    3 , 8
ORDER BY 5 DESC
limit 10;

/* insights
based on the analysis of non carded customer sales
Listerine holds the biggest share of sales in mouth wash category for non carded customers
sales of listerine in mouth wash caategory has gone down by a whoping 1.57 million compared to previous year
which is the major factor that caused the oversales in mouth and dental product category of retailer client
this is because of the incresed avrage price in this category by 23.61 unit. Also discount was reduced by over all 3 percent */

-- identify items PERFORMED well in  listerine category for 2010 and compare it with sales in 2011--

SELECT 
    t.CUSTOMER_TYPE,
    p.CATEGORY,
    p.BRAND,
    P.ITEM,
    COUNT(t.CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(t.NET_AMT), 0) AS PURCHASE_VALUE,
    ROUND(AVG(NET_AMT / ITEM_QTY), 2) AS AVERAGE_PRICE,
    ROUND(AVG(DISC_MARGIN) * 100) AS PERCENT_DISC,
    YEAR(t.TXN_DT) AS YEAR
FROM
    transactions t
        JOIN
    product p ON t.UPC_ID = p.UPC_id
WHERE
    p.CATEGORY = 'MOUTHWASH'
        AND t.CUSTOMER_TYPE = 'NO CARD'
        AND p.BRAND = 'LISTERINE'
        AND YEAR(t.TXN_DT) = "2010"
GROUP BY 3 , 4 , 9
ORDER BY 6 DESC
limit 5
;
-- top selling items are cool mints in listerine--
-- compare with 2011 -- 
## create temperory table for listerine products 

CREATE temporary table listerine
SELECT 
    t.CUSTOMER_TYPE,
    p.CATEGORY,
    p.BRAND,
    P.ITEM,
    COUNT(t.CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(t.NET_AMT), 0) AS PURCHASE_VALUE,
    ROUND(AVG(NET_AMT / ITEM_QTY), 2) AS AVERAGE_PRICE,
    ROUND(AVG(DISC_MARGIN) * 100) AS PERCENT_DISC,
    YEAR(t.TXN_DT) AS YEAR
FROM
    transactions t
        JOIN
    product p ON t.UPC_ID = p.UPC_id
WHERE
    p.CATEGORY = 'MOUTHWASH'
        AND t.CUSTOMER_TYPE = 'NO CARD'
        AND BRAND = 'LISTERINE'
GROUP BY 3 , 4 , 9
ORDER BY 6 DESC
;

SELECT * FROM listerine
WHERE ITEM IN ("COOL MINT 500ML" , "COOL MINT 250ML" , "COOL MINT 250ML" , "TOTAL CARE 750ML", "TARTAR 750ML", "COOL MINT 750ML") ;

 -- IDENTIFY WHICH RETAIL GROUP SELLS MOST MOUTH WASH PRODUCTS--
 
SELECT 
    t.CUSTOMER_TYPE,
	p.CATEGORY,
    s.RETAIL_GROUP,
    COUNT(t.CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(t.NET_AMT), 0) AS PURCHASE_VALUE,
    ROUND(AVG(DISC_MARGIN) * 100) AS PERCENT_DISC,
    YEAR(t.TXN_DT) AS YEAR
FROM
    transactions t
        JOIN
    product p ON t.UPC_ID = p.UPC_id
		JOIN
	store s ON t.STORE_ID = s.STORE_ID
WHERE p.CATEGORY = "MOUTHWASH" AND t.CUSTOMER_TYPE = "NO CARD"
GROUP BY 1, 2,  3 , 7
ORDER BY 3 DESC;

## INSIGHT : MOST OF THE SALES FOR MOUTH WASH  PRODUCT COMES FROM RETAILERS HYPERMARKET GROUP
## further analysis can be done using loactions of this hyerkaerket

SELECT 
    t.CUSTOMER_TYPE,
	p.CATEGORY,
    s.RETAIL_GROUP,
    s.AREA as LOCATION,
    COUNT(t.CUSTOMER_ID) AS TOTAL_PURCHASE,
    ROUND(SUM(t.NET_AMT), 0) AS PURCHASE_VALUE,
    ROUND(AVG(DISC_MARGIN) * 100) AS PERCENT_DISC,
    YEAR(t.TXN_DT) AS YEAR
FROM
    transactions t
        JOIN
    product p ON t.UPC_ID = p.UPC_id
		JOIN
	store s ON t.STORE_ID = s.STORE_ID
WHERE p.CATEGORY = "MOUTHWASH" AND t.CUSTOMER_TYPE = "NO CARD"
GROUP BY 1, 2,  4 , 8
ORDER BY 3 DESC;

## INSIGHT :  BANKOK AND PERIMETER LOCATION SALES MOST MOUTH WASH PRODUCTS IN NON CARDED CUSOMER CATEGORY --